print()
print('Buenos días')
print('Mi nombre es "main"')
print('Soy un programa bastante básico que le mostrará la información de mi creador:')
print()
print('Nombre:                   Daniel Augusto García Villatoro')
print('Carné No.:                1532522')
print('Universidad de estudio:   Universidad Rafael Landívar')
print('Carrera:                  Ingeniería en Informática y Sistemas')
print('Edad:                     17 años')
